Added || true when detecting the path of rpm

diff --git a/admin/install/install b/admin/install/install
--- a/admin/install/install
+++ b/admin/install/install
@@ -16,7 +16,9 @@ if [ -f /etc/debian_version ] ; then
 	. /usr/share/dtc/admin/install/functions
 fi
 
-RPM=`which rpm`
+# Find the rpm exec: it can be not present, thus the || to avoid
+# that this script fails
+RPM=`which rpm || true`
 if [ -x "$RPM" ] ; then
 	if rpm -q coreutils >/dev/null ; then
 		# Prepare everything
